[tool.poetry]
name = "ptorrent"
version = "0.1.0"
description = ""
authors = ["River Hermsen <riverhermsen@hotmail.nl>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
customtkinter = "^5.2.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
